
name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
     
      - name: Build Docker Image
        run: docker build -t ik3232/nodejson  .
      - name: Publish Image to docker hub
        run: docker push ik3232/nodejson:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull ik3232/nodejson:latest 
      - name: Delete old container
        run: docker rm -f nodejson-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejson-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' ik3232/nodejson
