name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: docker build -t ik3232/nodejson:latest .

      - name: Push Image to Docker Hub
        run: docker push ik3232/nodejson:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ik3232/nodejson:latest

      - name: Stop and remove old container if it exists
        run: |
          docker rm -f nodejson-container || true

      - name: Run new Docker container
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          docker run -d -p 4000:4000 --name nodejson-container \
          -e MONGO_URI="$MONGO_URI" \
          ik3232/nodejson:latest
